<?php

namespace NormasBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * FosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FosUserRepository extends EntityRepository
{

	public function obtenerDatos(){
        echo'<pre>';dump("Al repositorio si llega");exit; 
          echo'<pre>';dump("esto es una prueba");exit; 
return 1;
	 }
}
