<?php

namespace NormasBundle\Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;
//use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * GenResolucionRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenResolucionRepository extends EntityRepository
{
    public function obtenerDatos(){
        return 1; 
    }

	public function buscaResoluciones(){
        
	$query = "
    SELECT
    a.id as id, 
    b.nombre as nombre,
    a.rutCompania as rutCompania,
    a.mesInformado as mesInformado,
    a.resolucion as resolucion,
    a.fechaResolucion as fechaResolucion,
    a.ufPago as ufPago,
    a.fechaPago as fechaPago,
    a.activo as activo
	FROM NormasBundle\Entity\GenResolucion a
	INNER JOIN NormasBundle\Entity\GenCompania b WITH (b.id = a.rutCompania)
	";

    $query = $this->_em->createQuery($query);

    return $query->getArrayResult();
	}


}

