<?php

namespace NormasBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * GenTiporiesgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenTiporiesgoRepository extends EntityRepository
{
}
