<?php

namespace NormasBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * GenTemporadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenTemporadaRepository extends EntityRepository
{

public function buscaTemporada($idNsZhs)
{
    $query = "
    SELECT 
    gt.id as id,
    gt.temporada as temporada
    FROM NormasBundle\Entity\GenSacRubroZhs a
    INNER JOIN NormasBundle\Entity\NsZhs ns  WITH (ns.id = a.idNsZhs)
    INNER JOIN NormasBundle\Entity\GenSacRubroZhsTemporada gr WITH (a.id = gr.idGenSacRubroZhs)
    INNER JOIN NormasBundle\Entity\GenTemporadaVersion gs WITH (gr.idGenTemporadaVersion = gs.id)
    INNER JOIN NormasBundle\Entity\GenTemporada gt WITH (gs.idGenTemporada = gt.id)
    WHERE a.idNsZhs = :idNsZhs
    GROUP BY 
    gt.id,
    gt.temporada
    ";

    $query = $this->_em->createQuery($query);
    if($idNsZhs != null){
    $query->setParameter('idNsZhs',$idNsZhs);
    }
    return $query->getArrayResult();
}

  public function buscaTemporadaVersion($idGenTemporada,$idNsZhs){

    // echo'<pre>';var_dump("Hasta acá va el mambo");exit;
    $query = "
    SELECT 
    gs.id as id,
    gs.temporadaVersion as temporadaVersion
    FROM NormasBundle\Entity\GenSacRubroZhs a
    INNER JOIN NormasBundle\Entity\NsZhs ns  WITH (ns.id = a.idNsZhs)
    INNER JOIN NormasBundle\Entity\GenSacRubroZhsTemporada gr WITH (a.id = gr.idGenSacRubroZhs)
    INNER JOIN NormasBundle\Entity\GenTemporadaVersion gs WITH (gr.idGenTemporadaVersion = gs.id)
    INNER JOIN NormasBundle\Entity\GenTemporada gt WITH (gs.idGenTemporada = gt.id)
    WHERE a.idNsZhs = :idNsZhs
    AND gt.id = :idGenTemporada
    GROUP BY 
    gs.id,
    gs.temporadaVersion
    ";

    $query = $this->_em->createQuery($query);
    
    if($idNsZhs != null){
    $query->setParameter('idNsZhs',$idNsZhs);
    }
    
    if($idGenTemporada != null){
    $query->setParameter('idGenTemporada',$idGenTemporada);
    }
    
   // echo'<pre>';var_dump("Hasta acá va el mambo");exit;
    return $query->getArrayResult(); 
  }


}



