<?php

namespace NormasBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * NsValoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NsValoresRepository extends EntityRepository
{
}
