<?php

namespace NormasBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * NsZhsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NsZhsRepository extends EntityRepository
{
}
