// Generated by CoffeeScript 1.6.2

  var app = angular.module('chosenExampleApp', ['localytics.directives']);

       /*app.config(function($routeProvider){
        $routeProvider
            .when("/", {
                controller: "appCtrl",
                controllerAs: "vm",
                templateUrl: "home.html"
            })
            .when("/descargas", {
                controller: "appCtrl",
                controllerAs: "vm",
                templateUrl: "descargas.html"
            })
            .when("/rutaPrueba", {
                controller: "appCtrl",
                controllerAs: "vm",
                templateUrl: "prueba.html"
            })
            .when("/opciones", {
                controller: "appCtrl",
                controllerAs: "vm",
                templateUrl: "opciones.html"
            });
      });
*/

      app.controller('tableChosenCtrl', ['$scope', '$q', '$timeout', function($scope, $q, $timeout){
        
        console.log("la carga");
        console.log("aca si entra 1");
        var simulateAjax;  

    /*  Esta es una promesa
        simulateAjax = function(result) {
        var deferred, fn;
        deferred = $q.defer();
        fn = function() {
          return deferred.resolve(result);
        };

        $timeout(fn, 3000);
        return deferred.promise;
        };*/

        simulateAjax(['grooo', 'wowowowow', 'lakakalakakl', 'yadayada','poracavaelmambo', 'insight', 'delve', 'synergy'])
        .then(function(result) {
        return $scope.optionsFromQuery = result;
        });

      }]);

     /*   app.controller('tableChosenCtrl', ['$scope', '$q', '$timeout', function($scope, $q, $timeout){
        console.log("aca si entra 2");
        return 1;
      }]);*/

     /*   app.controller('ChosenCtrl',['$scope', '$http','$stateParams','$log', function ($scope, $http,$stateParams,$log) {
        $scope.$on('$viewContentLoaded', function() {
    
          $http.get(Routing.generate('agroseguros_mandato_online_historial_detalle_datos_beneficiario',{idPropuesta:$stateParams.idPropuesta},true)).then(function (data){
              $http.de*/
            /*Cuando se mandan parametros
            $http.get(Routing.generate('agroseguros_mandato_online_historial_detalle_datos_beneficiario',{idPropuesta:$stateParams.idPropuesta},true)).then(function (data){
            
            //$log.info(data.data);
            $scope.datos = data.data;
            */
     /*     });                
        });
      }]);
*/

